package server

import (
	"sesi8-latihan/server/controllers"

	"sesi8-latihan/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type Router struct {
	people *controllers.PersonController
}

func NewRouter(people *controllers.PersonController) *Router {
	return &Router{people: people}
}

func (r *Router) Start(port string) {
	docs.SwaggerInfo.Title = "Swagger Orders API"
	docs.SwaggerInfo.Description = "Sample API Spec for Orders"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:4000"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	router := gin.Default()

	router.GET("/people", r.people.GetPeople)
	router.GET("/people_detail/:Id", r.people.GetPeopleById)
	router.POST("/people", r.people.CreatePeople)
	router.DELETE("/people/:Id", r.people.DeletePeople)
	router.PATCH("/people/:Id", r.people.UpdatePeople)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.Run(port)
}
