package server

import (
	"assigment2/server/controllers"

	"assigment2/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type Router struct {
	order *controllers.OrdersController
}

func NewRouter(order *controllers.OrdersController) *Router {
	return &Router{
		order: order,
	}
}

func (r *Router) Start(port string) {
	docs.SwaggerInfo.Title = "Swagger Orders API"
	docs.SwaggerInfo.Description = "Sample API Spec for Orders"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:9000"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	router := gin.Default()
	router.POST("/orders", r.order.CreateOrders)
	router.GET("/orders", r.order.GetOrders)
	router.DELETE("/orders/:id", r.order.DeleteOrders)
	router.PATCH("/orders/:id", r.order.UpdateOrders)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.Run(port)
}
